rosemary: Drop majority of Mediatek JARs
* Used as boot JARs, but causing build to fail.

```
Error: out/target/common/obj/JAVA_LIBRARIES/mediatek-common_intermediates/classes.jar does not contain any class files.
Error: out/target/common/obj/JAVA_LIBRARIES/mediatek-framework_intermediates/classes.jar does not contain any class files.
Error: out/target/common/obj/JAVA_LIBRARIES/mediatek-ims-base_intermediates/classes.jar does not contain any class files.
Error: out/target/common/obj/JAVA_LIBRARIES/mediatek-ims-common_intermediates/classes.jar does not contain any class files.
Error: out/target/common/obj/JAVA_LIBRARIES/mediatek-telecom-common_intermediates/classes.jar does not contain any class files.
Error: out/target/common/obj/JAVA_LIBRARIES/mediatek-telephony-base_intermediates/classes.jar does not contain any class files.
Error: out/target/common/obj/JAVA_LIBRARIES/mediatek-telephony-common_intermediates/classes.jar does not contain any class files.
```

Signed-off-by: Beru Hinode <windowz414@1337.lgbt>